[server]
url = "https://localhost:10101"
cert = "tls/cert.pem"
key = "tls/key.pem"
redirect_from = [
    "https://localhost:10081",
    "https://localhost:10082",
]

[log]
actix_web = "debug"
webapp = "trace"

[postgres]
host = "127.0.0.1"
port = "54322"
username = "webapp"
password = "webapp"
database = "webapp"
