version: '3.0'

services:
  postgres_dev:
    build: './postgres'
    ports:
      - "54322:5432"
    environment:
      - POSTGRES_DB=webapp
      - POSTGRES_USER=webapp
      - POSTGRES_PASSWORD=webapp
    networks:
      - dev

networks:
  dev:
