version: '3.0'

services:
  postgres:
    build: './postgres'
    env_file:
      - ./.env
    ports:
      - "54322:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
